export default [
  {
    name: "Default",
    value: {
      color: "white",
      url:"docs.motorcortexjs.com",
      brandName:"Motorcortex",
      textColor: "#121212",
      firstSlideImageOne:"https://donkeyclip.github.io/product-promo/demo/assets/first-slide1.jpg",
      firstSlideImageTwo:"https://donkeyclip.github.io/product-promo/demo/assets/first-slide2.jpg",
      transitionHeading:"Choose Convenience",
      transitionSlogan:"Shop with us",
      bestProductsHeading:"Best Products",
      bestProductsSlogan:"Wide assortment New Collection",
      bestProductImages:["https://donkeyclip.github.io/product-promo/demo/assets/bp1.jpg","https://donkeyclip.github.io/product-promo/demo/assets/bp2.jpg","https://donkeyclip.github.io/product-promo/demo/assets/bp3.jpg"],
      opHeading:"Online Promotions",
      opSlogan:"Best Prices",
      opImages:["https://donkeyclip.github.io/product-promo/demo/assets/op1.jpg","https://donkeyclip.github.io/product-promo/demo/assets/op2.jpg","https://donkeyclip.github.io/product-promo/demo/assets/op3.jpg"],
      fdHeading:"Fast delivery",
      fdSlogan:"Free from 50$ prurchese",
      fdImages:["https://donkeyclip.github.io/product-promo/demo/assets/fd1.jpg","https://donkeyclip.github.io/product-promo/demo/assets/fd2.jpg","https://donkeyclip.github.io/product-promo/demo/assets/fd3.jpg","https://donkeyclip.github.io/product-promo/demo/assets/fd4.jpg","https://donkeyclip.github.io/product-promo/demo/assets/fd5.jpg"]
    },
  },
  {
    name: "Dark",
    value: {
      color: "#121212",
      url:"docs.motorcortexjs.com",
      brandName:"Motorcortex",
      textColor: "#fff",
      firstSlideImageOne:"https://donkeyclip.github.io/product-promo/demo/assets/first-slide1.jpg",
      firstSlideImageTwo:"https://donkeyclip.github.io/product-promo/demo/assets/first-slide2.jpg",
      transitionHeading:"Choose Convenience",
      transitionSlogan:"Shop with us",
      bestProductsHeading:"Best Products",
      bestProductsSlogan:"Wide assortment New Collection",
      bestProductImages:["https://donkeyclip.github.io/product-promo/demo/assets/bp1.jpg","https://donkeyclip.github.io/product-promo/demo/assets/bp2.jpg","https://donkeyclip.github.io/product-promo/demo/assets/bp3.jpg"],
      opHeading:"Online Promotions",
      opSlogan:"Best Prices",
      opImages:["https://donkeyclip.github.io/product-promo/demo/assets/op1.jpg","https://donkeyclip.github.io/product-promo/demo/assets/op2.jpg","https://donkeyclip.github.io/product-promo/demo/assets/op3.jpg"],
      fdHeading:"Online Promotions",
      fdSlogan:"Free from 50$ prurchese",
      fdImages:["https://donkeyclip.github.io/product-promo/demo/assets/fd1.jpg","https://donkeyclip.github.io/product-promo/demo/assets/fd2.jpg","https://donkeyclip.github.io/product-promo/demo/assets/fd3.jpg","https://donkeyclip.github.io/product-promo/demo/assets/fd4.jpg","https://donkeyclip.github.io/product-promo/demo/assets/fd5.jpg"]
    },
  },
];
